### ISSUE TITLE
colab

### ISSUE THREAD

**Issue by ghost** [KimythAnly/AGAIN-VC#1]
Hi can you please add a google colab for inference thanks

**Comment by KimythAnly** [comment]
Hi, I add a jupyter notebook for inference. 
Please take a look and see if there is any problem. Thanks!

**Comment by KimythAnly** [comment]
Thanks for the suggestion!
I created a google colab for inference, and the link can also be found in README.md
https://colab.research.google.com/drive/1Q3v2bTKPV0jB1F_dBT1YuqINDq9a52qO?usp=sharing

**Comment by ghost** [comment]
thanks
