### ISSUE TITLE
关于训练集中train与dev的比例问题

### ISSUE THREAD

**Issue by chestnutly** [KimythAnly/AGAIN-VC#11]
你好，该模型效果十分优秀，但是在训练过程中我有一些问题想请教，关于在训练集中train与dev的比例，假设我有一万条数据，比例设置为split_all:      
    train: 9000
    dev: 1000
为何输出的index字典中train的数量为9000，dev的数量为10000呢？而且关于其中分割的函数写法：def split(self, file_list, split_all, split_train):
        raise NotImplementedError
这样的写法为何能正常运行输出index呢？如有空解答，万分感谢！！

**Comment by lqsunshine** [comment]
> 你好，该模型效果十分优秀，但是在训练过程中我有一些问题想请教，关于在训练集中train与dev的比例，假设我有一万条数据，比例设置为split_all: train: 9000 dev: 1000 为何输出的index字典中train的数量为9000，dev的数量为10000呢？而且关于其中分割的函数写法：def split(self, file_list, split_all, split_train): raise NotImplementedError 这样的写法为何能正常运行输出index呢？如有空解答，万分感谢！！

你解决了吗，我也遇到这个问题。

**Comment by lqsunshine** [comment]
> > 你好，该模型效果十分优秀，但是在训练过程中我有一些问题想请教，关于在训练集中train与dev的比例，假设我有一万条数据，比例设置为split_all: train: 9000 dev: 1000 为何输出的index字典中train的数量为9000，dev的数量为10000呢？而且关于其中分割的函数写法：def split(self, file_list, split_all, split_train): raise NotImplementedError 这样的写法为何能正常运行输出index呢？如有空解答，万分感谢！！
> 
> 你解决了吗，我也遇到这个问题。

一共109人，80人的前200个talk做训练，80人中超过200的其余talk做验证。109人外的其余20人的所以talk做测试吧
