### ISSUE TITLE
pretrained model links

### ISSUE THREAD

**Issue by ghost** [KimythAnly/AGAIN-VC#4]
Hi the pretrained models links are down
also the config folder has .example file extension added after removing that it works for inference

**Comment by KimythAnly** [comment]
Hi
The pretrained models links are fixed and available now. Also I remove the *.example files and add *.yaml files under `./config/`.

**Comment by ghost** [comment]
thanks

**Comment by kay9012** [comment]
> Hi The pretrained models links are fixed and available now. Also I remove the *.example files and add *.yaml files under `./config/`.

it seems that the pretrained models links are down again

**Comment by KimythAnly** [comment]
> > Hi The pretrained models links are fixed and available now. Also I remove the *.example files and add *.yaml files under `./config/`.
> 
> it seems that the pretrained models links are down again

Hi, the pretrained model is expired and I thought I didn't have any backup for that.
I'm sorry for that ><
