### ISSUE TITLE
Not great as demo

### ISSUE THREAD

**Issue by zhangxinaaaa** [KimythAnly/AGAIN-VC#9]
Hey, thank you for your great work!
i used your pretrained model file to inference the demo samples. But the conversion effect is not as perfect as the demo's.
Is it beause of the pretrained model need more time training?

**Comment by KimythAnly** [comment]
Hi, could you provide the .wav files?

**Comment by KimythAnly** [comment]
Hi, could you provide your generated .wav files? Thanks.

**Comment by zhangxinaaaa** [comment]
Here is the notebook link [that](https://colab.research.google.com/drive/1FdhapPWBHHVVSkGOOUveSkJMbEBjZ1S-?usp=sharing) i inference the demo samples, you can hear and download the generated wave file. Thanks for your time and reply!

**Comment by KimythAnly** [comment]
Hi, the converted sample you used in the colab is a sample generated by AdaIN-VC, not our proposed model, AGAIN-VC.
Besides, the released pretrained model is trained using the latest code on this repo, thus the generated result might not be the same as the ones on the demo page. Thanks!

**Comment by zhangxinaaaa** [comment]
Can you offer the code that generate the demo samples? I'm working on it and wish to learn from the code.Thank you very much

**Comment by KimythAnly** [comment]
Do you mean the models trained using other methods (AdaIN-VC, VQVC+, AutoVC)?

**Comment by zhangxinaaaa** [comment]
Yes, thank you very much!

**Comment by KimythAnly** [comment]
Hi, I'm working on integrating these models. Yet these models are open-source, you may try to train these models using their released code on GitHub. The thing you need to pay attention to is that we use MelGAN as the vocoder for every model on the demo page.

**Comment by zhangxinaaaa** [comment]
Ok! And by the way,  I enjoy listening to Hung-yi Lee's lessons very much,  thanks for your hard works!
